// <auto-generated />
using System;
using CiudApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CiudApp.Data.Migrations
{
    [DbContext(typeof(CiudAppContext))]
    [Migration("20250517110129_Migracion3")]
    partial class Migracion3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CiudApp.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Poblacion")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5265),
                            Nombre = "Zaragoza",
                            Pais = "España",
                            Poblacion = 700000,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5326),
                            Nombre = "Londres",
                            Pais = "Inglaterra",
                            Poblacion = 10000000,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 3,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5331),
                            Nombre = "Sevilla",
                            Pais = "España",
                            Poblacion = 688711,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 4,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5336),
                            Nombre = "Buenos Aires",
                            Pais = "Argentina",
                            Poblacion = 2890000,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 5,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5340),
                            Nombre = "Lisboa",
                            Pais = "Portugal",
                            Poblacion = 504718,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 6,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5344),
                            Nombre = "Venecia",
                            Pais = "Italia",
                            Poblacion = 261905,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 7,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5348),
                            Nombre = "Barcelona",
                            Pais = "España",
                            Poblacion = 1620000,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 8,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5352),
                            Nombre = "París",
                            Pais = "Francia",
                            Poblacion = 2148000,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 9,
                            FechaRegistro = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5356),
                            Nombre = "Tokio",
                            Pais = "Japón",
                            Poblacion = 13960000,
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("CiudApp.Models.Resena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Recomendacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.ToTable("Resenas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calificacion = 5,
                            CiudadId = 1,
                            Descripcion = "El transporte fue eficiente y fácil de usar.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5627),
                            Recomendacion = true,
                            Titulo = "Una experiencia maravillosa"
                        },
                        new
                        {
                            Id = 2,
                            Calificacion = 4,
                            CiudadId = 1,
                            Descripcion = "Tuve una experiencia muy positiva, lo recomiendo.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5636),
                            Recomendacion = true,
                            Titulo = "Volvería sin dudarlo"
                        },
                        new
                        {
                            Id = 3,
                            Calificacion = 5,
                            CiudadId = 1,
                            Descripcion = "Tuve una experiencia muy positiva, lo recomiendo.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5640),
                            Recomendacion = true,
                            Titulo = "Inolvidable"
                        },
                        new
                        {
                            Id = 4,
                            Calificacion = 1,
                            CiudadId = 1,
                            Descripcion = "Todo fue extremadamente caro para lo que ofrecía.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5644),
                            Recomendacion = false,
                            Titulo = "Mal clima"
                        },
                        new
                        {
                            Id = 5,
                            Calificacion = 2,
                            CiudadId = 1,
                            Descripcion = "Todo fue extremadamente caro para lo que ofrecía.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5648),
                            Recomendacion = false,
                            Titulo = "Experiencia regular"
                        },
                        new
                        {
                            Id = 6,
                            Calificacion = 2,
                            CiudadId = 1,
                            Descripcion = "Esperaba más, me decepcionó bastante.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5652),
                            Recomendacion = false,
                            Titulo = "Muy sucia"
                        },
                        new
                        {
                            Id = 7,
                            Calificacion = 5,
                            CiudadId = 2,
                            Descripcion = "Mucho que ver y disfrutar, fue un gran viaje.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5656),
                            Recomendacion = true,
                            Titulo = "Inolvidable"
                        },
                        new
                        {
                            Id = 8,
                            Calificacion = 5,
                            CiudadId = 2,
                            Descripcion = "Mucho que ver y disfrutar, fue un gran viaje.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5660),
                            Recomendacion = true,
                            Titulo = "Encantadora"
                        },
                        new
                        {
                            Id = 9,
                            Calificacion = 4,
                            CiudadId = 2,
                            Descripcion = "La ciudad es hermosa y está llena de historia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5664),
                            Recomendacion = true,
                            Titulo = "Inolvidable"
                        },
                        new
                        {
                            Id = 10,
                            Calificacion = 3,
                            CiudadId = 2,
                            Descripcion = "Poca oferta cultural y muchas obras en las calles.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5668),
                            Recomendacion = false,
                            Titulo = "Demasiado caro"
                        },
                        new
                        {
                            Id = 11,
                            Calificacion = 2,
                            CiudadId = 2,
                            Descripcion = "Esperaba más, me decepcionó bastante.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5672),
                            Recomendacion = false,
                            Titulo = "Demasiado caro"
                        },
                        new
                        {
                            Id = 12,
                            Calificacion = 1,
                            CiudadId = 2,
                            Descripcion = "Todo fue extremadamente caro para lo que ofrecía.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5675),
                            Recomendacion = false,
                            Titulo = "No volvería"
                        },
                        new
                        {
                            Id = 13,
                            Calificacion = 4,
                            CiudadId = 3,
                            Descripcion = "Mucho que ver y disfrutar, fue un gran viaje.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5679),
                            Recomendacion = true,
                            Titulo = "Una experiencia maravillosa"
                        },
                        new
                        {
                            Id = 14,
                            Calificacion = 4,
                            CiudadId = 3,
                            Descripcion = "Perfecta para unas vacaciones tranquilas y culturales.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5683),
                            Recomendacion = true,
                            Titulo = "Volvería sin dudarlo"
                        },
                        new
                        {
                            Id = 15,
                            Calificacion = 5,
                            CiudadId = 3,
                            Descripcion = "Las personas fueron muy amables y la comida deliciosa.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5687),
                            Recomendacion = true,
                            Titulo = "Inolvidable"
                        },
                        new
                        {
                            Id = 16,
                            Calificacion = 3,
                            CiudadId = 3,
                            Descripcion = "Tuve muchos problemas con el transporte.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5691),
                            Recomendacion = false,
                            Titulo = "Decepcionante"
                        },
                        new
                        {
                            Id = 17,
                            Calificacion = 3,
                            CiudadId = 3,
                            Descripcion = "Todo fue extremadamente caro para lo que ofrecía.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5695),
                            Recomendacion = false,
                            Titulo = "Experiencia regular"
                        },
                        new
                        {
                            Id = 18,
                            Calificacion = 2,
                            CiudadId = 3,
                            Descripcion = "No me sentí seguro durante mi estancia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5698),
                            Recomendacion = false,
                            Titulo = "Demasiado caro"
                        },
                        new
                        {
                            Id = 19,
                            Calificacion = 5,
                            CiudadId = 4,
                            Descripcion = "Mucho que ver y disfrutar, fue un gran viaje.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5702),
                            Recomendacion = true,
                            Titulo = "Muy recomendable"
                        },
                        new
                        {
                            Id = 20,
                            Calificacion = 4,
                            CiudadId = 4,
                            Descripcion = "El transporte fue eficiente y fácil de usar.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5706),
                            Recomendacion = true,
                            Titulo = "Me encantó"
                        },
                        new
                        {
                            Id = 21,
                            Calificacion = 4,
                            CiudadId = 4,
                            Descripcion = "El transporte fue eficiente y fácil de usar.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5710),
                            Recomendacion = true,
                            Titulo = "Volvería sin dudarlo"
                        },
                        new
                        {
                            Id = 22,
                            Calificacion = 1,
                            CiudadId = 4,
                            Descripcion = "No me sentí seguro durante mi estancia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5723),
                            Recomendacion = false,
                            Titulo = "Mal clima"
                        },
                        new
                        {
                            Id = 23,
                            Calificacion = 2,
                            CiudadId = 4,
                            Descripcion = "Esperaba más, me decepcionó bastante.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5727),
                            Recomendacion = false,
                            Titulo = "Muy sucia"
                        },
                        new
                        {
                            Id = 24,
                            Calificacion = 3,
                            CiudadId = 4,
                            Descripcion = "Poca oferta cultural y muchas obras en las calles.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5731),
                            Recomendacion = false,
                            Titulo = "No volvería"
                        },
                        new
                        {
                            Id = 25,
                            Calificacion = 5,
                            CiudadId = 5,
                            Descripcion = "La ciudad es hermosa y está llena de historia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5735),
                            Recomendacion = true,
                            Titulo = "Inolvidable"
                        },
                        new
                        {
                            Id = 26,
                            Calificacion = 4,
                            CiudadId = 5,
                            Descripcion = "Las personas fueron muy amables y la comida deliciosa.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5738),
                            Recomendacion = true,
                            Titulo = "Encantadora"
                        },
                        new
                        {
                            Id = 27,
                            Calificacion = 5,
                            CiudadId = 5,
                            Descripcion = "El transporte fue eficiente y fácil de usar.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5742),
                            Recomendacion = true,
                            Titulo = "Volvería sin dudarlo"
                        },
                        new
                        {
                            Id = 28,
                            Calificacion = 3,
                            CiudadId = 5,
                            Descripcion = "La ciudad estaba abarrotada y sucia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5746),
                            Recomendacion = false,
                            Titulo = "Mal clima"
                        },
                        new
                        {
                            Id = 29,
                            Calificacion = 1,
                            CiudadId = 5,
                            Descripcion = "Esperaba más, me decepcionó bastante.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5750),
                            Recomendacion = false,
                            Titulo = "Experiencia regular"
                        },
                        new
                        {
                            Id = 30,
                            Calificacion = 3,
                            CiudadId = 5,
                            Descripcion = "No me sentí seguro durante mi estancia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5754),
                            Recomendacion = false,
                            Titulo = "Decepcionante"
                        },
                        new
                        {
                            Id = 31,
                            Calificacion = 4,
                            CiudadId = 6,
                            Descripcion = "La ciudad es hermosa y está llena de historia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5758),
                            Recomendacion = true,
                            Titulo = "Me encantó"
                        },
                        new
                        {
                            Id = 32,
                            Calificacion = 4,
                            CiudadId = 6,
                            Descripcion = "Tuve una experiencia muy positiva, lo recomiendo.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5761),
                            Recomendacion = true,
                            Titulo = "Volvería sin dudarlo"
                        },
                        new
                        {
                            Id = 33,
                            Calificacion = 4,
                            CiudadId = 6,
                            Descripcion = "La ciudad es hermosa y está llena de historia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5765),
                            Recomendacion = true,
                            Titulo = "Volvería sin dudarlo"
                        },
                        new
                        {
                            Id = 34,
                            Calificacion = 3,
                            CiudadId = 6,
                            Descripcion = "Todo fue extremadamente caro para lo que ofrecía.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5770),
                            Recomendacion = false,
                            Titulo = "Muy sucia"
                        },
                        new
                        {
                            Id = 35,
                            Calificacion = 2,
                            CiudadId = 6,
                            Descripcion = "Poca oferta cultural y muchas obras en las calles.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5774),
                            Recomendacion = false,
                            Titulo = "Experiencia regular"
                        },
                        new
                        {
                            Id = 36,
                            Calificacion = 2,
                            CiudadId = 6,
                            Descripcion = "No me sentí seguro durante mi estancia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5778),
                            Recomendacion = false,
                            Titulo = "Mal clima"
                        },
                        new
                        {
                            Id = 37,
                            Calificacion = 4,
                            CiudadId = 7,
                            Descripcion = "Las personas fueron muy amables y la comida deliciosa.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5781),
                            Recomendacion = true,
                            Titulo = "Me encantó"
                        },
                        new
                        {
                            Id = 38,
                            Calificacion = 5,
                            CiudadId = 7,
                            Descripcion = "El transporte fue eficiente y fácil de usar.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5785),
                            Recomendacion = true,
                            Titulo = "Me encantó"
                        },
                        new
                        {
                            Id = 39,
                            Calificacion = 5,
                            CiudadId = 7,
                            Descripcion = "Perfecta para unas vacaciones tranquilas y culturales.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5789),
                            Recomendacion = true,
                            Titulo = "Volvería sin dudarlo"
                        },
                        new
                        {
                            Id = 40,
                            Calificacion = 2,
                            CiudadId = 7,
                            Descripcion = "Todo fue extremadamente caro para lo que ofrecía.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5793),
                            Recomendacion = false,
                            Titulo = "Decepcionante"
                        },
                        new
                        {
                            Id = 41,
                            Calificacion = 3,
                            CiudadId = 7,
                            Descripcion = "No me sentí seguro durante mi estancia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5797),
                            Recomendacion = false,
                            Titulo = "Decepcionante"
                        },
                        new
                        {
                            Id = 42,
                            Calificacion = 3,
                            CiudadId = 7,
                            Descripcion = "Esperaba más, me decepcionó bastante.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5801),
                            Recomendacion = false,
                            Titulo = "Experiencia regular"
                        },
                        new
                        {
                            Id = 43,
                            Calificacion = 5,
                            CiudadId = 8,
                            Descripcion = "Tuve una experiencia muy positiva, lo recomiendo.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5804),
                            Recomendacion = true,
                            Titulo = "Muy recomendable"
                        },
                        new
                        {
                            Id = 44,
                            Calificacion = 5,
                            CiudadId = 8,
                            Descripcion = "Perfecta para unas vacaciones tranquilas y culturales.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5809),
                            Recomendacion = true,
                            Titulo = "Inolvidable"
                        },
                        new
                        {
                            Id = 45,
                            Calificacion = 4,
                            CiudadId = 8,
                            Descripcion = "La ciudad es hermosa y está llena de historia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5813),
                            Recomendacion = true,
                            Titulo = "Volvería sin dudarlo"
                        },
                        new
                        {
                            Id = 46,
                            Calificacion = 3,
                            CiudadId = 8,
                            Descripcion = "La ciudad estaba abarrotada y sucia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5816),
                            Recomendacion = false,
                            Titulo = "Decepcionante"
                        },
                        new
                        {
                            Id = 47,
                            Calificacion = 2,
                            CiudadId = 8,
                            Descripcion = "Esperaba más, me decepcionó bastante.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5820),
                            Recomendacion = false,
                            Titulo = "Demasiado caro"
                        },
                        new
                        {
                            Id = 48,
                            Calificacion = 2,
                            CiudadId = 8,
                            Descripcion = "No me sentí seguro durante mi estancia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5824),
                            Recomendacion = false,
                            Titulo = "Experiencia regular"
                        },
                        new
                        {
                            Id = 49,
                            Calificacion = 4,
                            CiudadId = 9,
                            Descripcion = "Las personas fueron muy amables y la comida deliciosa.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5828),
                            Recomendacion = true,
                            Titulo = "Encantadora"
                        },
                        new
                        {
                            Id = 50,
                            Calificacion = 4,
                            CiudadId = 9,
                            Descripcion = "Perfecta para unas vacaciones tranquilas y culturales.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5832),
                            Recomendacion = true,
                            Titulo = "Muy recomendable"
                        },
                        new
                        {
                            Id = 51,
                            Calificacion = 4,
                            CiudadId = 9,
                            Descripcion = "Perfecta para unas vacaciones tranquilas y culturales.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5835),
                            Recomendacion = true,
                            Titulo = "Encantadora"
                        },
                        new
                        {
                            Id = 52,
                            Calificacion = 1,
                            CiudadId = 9,
                            Descripcion = "La ciudad estaba abarrotada y sucia.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5839),
                            Recomendacion = false,
                            Titulo = "Experiencia regular"
                        },
                        new
                        {
                            Id = 53,
                            Calificacion = 2,
                            CiudadId = 9,
                            Descripcion = "Todo fue extremadamente caro para lo que ofrecía.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5843),
                            Recomendacion = false,
                            Titulo = "Mal clima"
                        },
                        new
                        {
                            Id = 54,
                            Calificacion = 1,
                            CiudadId = 9,
                            Descripcion = "Poca oferta cultural y muchas obras en las calles.",
                            Fecha = new DateTime(2025, 5, 17, 13, 1, 28, 657, DateTimeKind.Local).AddTicks(5847),
                            Recomendacion = false,
                            Titulo = "Mal clima"
                        });
                });

            modelBuilder.Entity("CiudApp.Models.Resena", b =>
                {
                    b.HasOne("CiudApp.Models.Ciudad", "Ciudad")
                        .WithMany("Resenas")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("CiudApp.Models.Ciudad", b =>
                {
                    b.Navigation("Resenas");
                });
#pragma warning restore 612, 618
        }
    }
}
