// <auto-generated />
using System;
using CiudApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CiudApp.Data.Migrations
{
    [DbContext(typeof(CiudAppContext))]
    [Migration("20250516111352_Migracoin1")]
    partial class Migracoin1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CiudApp.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Poblacion")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaRegistro = new DateTime(2025, 5, 16, 13, 13, 51, 590, DateTimeKind.Local).AddTicks(1974),
                            Nombre = "Zaragoza",
                            Pais = "España",
                            Poblacion = 700000,
                            SoftDelete = false
                        },
                        new
                        {
                            Id = 2,
                            FechaRegistro = new DateTime(2025, 5, 16, 13, 13, 51, 590, DateTimeKind.Local).AddTicks(2022),
                            Nombre = "Londres",
                            Pais = "Inglaterra",
                            Poblacion = 10000000,
                            SoftDelete = false
                        });
                });

            modelBuilder.Entity("CiudApp.Models.Resena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Recomendacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CiudadId");

                    b.ToTable("Resena");
                });

            modelBuilder.Entity("CiudApp.Models.Resena", b =>
                {
                    b.HasOne("CiudApp.Models.Ciudad", "Ciudad")
                        .WithMany("Resenas")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("CiudApp.Models.Ciudad", b =>
                {
                    b.Navigation("Resenas");
                });
#pragma warning restore 612, 618
        }
    }
}
