version: '3.8'

networks:
  backend:

volumes:
  mariadb-data:

services:
  mariadb:
    image: mariadb:latest
    # container_name: mariadb
    networks:
      - backend
    # Primero el host, luego el contendor
    ports:
      - 3307:3306
    # volumes:
    #  - /tmp/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=mypassword
    # Defino un service_healthy
    # Sacado de la web de mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    ports:
      - 8080:8080
    networks:
      - backend
    build:
      context: ./ciudapp-backend
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy

  frontend:
    ports:
      - 80:8080
    networks:
      - backend
    build:
      context: ./ciudapp-frontend
    depends_on:
      - backend
