apiVersion: v1
kind: Service
metadata:
  name: ciudapp-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ciudapp-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciudapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ciudapp-backend
  template:
    metadata:
      labels:
        app: ciudapp-backend
    spec:
      containers:
      - name: ciudapp-backend
        image: rlsanjose/ciudapp-backend-cloud:1.0
        ports:
        - containerPort: 8080
